# Generated by Django 4.0.6 on 2022-09-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_style',
            field=models.CharField(blank=True, choices=[('orange', 'orange'), ('purple', 'purple'), ('aquamarine', 'aquamarine'), ('aqua', 'aqua'), ('beige', 'beige'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, choices=[('black', 'black'), ('light', 'light'), ('dark', 'dark')], max_length=100, null=True),
        ),
    ]
