# Generated by Django 3.2.6 on 2022-09-23 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
