# Generated by Django 3.2.6 on 2022-09-26 18:05

from django.db import migrations
import user.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=user.fields.CompressedImageField(blank=True, default='media/images/default.png', null=True, quality=75, upload_to=''),
        ),
    ]
