# Generated by Django 3.2.6 on 2022-10-04 14:30

from django.db import migrations
import user.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=user.fields.CompressedImageField(blank=True, default='https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bGVuc3xlbnwwfHwwfHw%3D&w=1000&q=80', null=True, quality=75, upload_to=''),
        ),
    ]
