# Generated by Django 3.2.6 on 2022-10-05 17:35

from django.db import migrations
import user.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=user.fields.CompressedImageField(blank=True, default='cameraimg.png', null=True, quality=75, upload_to=''),
        ),
    ]
